---
title: "git_01"
author: "Lelainy Saavedra"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->You, Love, and I  
(He whispers) You and I,  
And if no more than you and I  
What care you or I?  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,  
Some say in ice.  
From what I've tasted of desire   
I hold with those who favor fire.  
But if I had to perish twice,  
 


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shinning on the sea,  
Shinning with all his might:  
He did his very best to make  
The billows smooth and bright-  
And this was odd, because it was  
The middle of the night.  

The moon was shinning sulkily,  
Because she thought the sun  
Had got no bussiness to be there  
After the day was done-  
"Its very rude of him", she said,  
"To come and spoil the fun!".  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Forgive me if I stumble and fall,  
For I know not how  
To love too well,  
I am clumsy  
and my words do not form as I wish  
so let me kiss you instead  
and let my lips paint for you,  
All the pictures that my clumsy heart cannot.  

